local u = require('adwaita.utils')
local colors = u.gen_colors()

local hl = u.highlight

local M = {}

local set_terminal_color = function()
    vim.g.terminal_color_0 = colors.terminal_dark.Color0
    vim.g.terminal_color_1 = colors.terminal_dark.Color1
    vim.g.terminal_color_2 = colors.terminal_dark.Color2
    vim.g.terminal_color_3 = colors.terminal_dark.Color3
    vim.g.terminal_color_4 = colors.terminal_dark.Color4
    vim.g.terminal_color_5 = colors.terminal_dark.Color5
    vim.g.terminal_color_6 = colors.terminal_dark.Color6
    vim.g.terminal_color_7 = colors.terminal_dark.Color7
    vim.g.terminal_color_8 = colors.terminal_dark.Color8
    vim.g.terminal_color_9 = colors.terminal_dark.Color9
    vim.g.terminal_color_10 = colors.terminal_dark.Color10
    vim.g.terminal_color_11 = colors.terminal_dark.Color11
    vim.g.terminal_color_12 = colors.terminal_dark.Color12
    vim.g.terminal_color_13 = colors.terminal_dark.Color13
    vim.g.terminal_color_14 = colors.terminal_dark.Color14
    vim.g.terminal_color_15 = colors.terminal_dark.Color15
    vim.g.terminal_color_background = colors.terminal_dark.Background
    vim.g.terminal_color_foreground = colors.terminal_dark.Foreground
end

M.set = function()
    set_terminal_color()

    -- UI highlight
    hl('Normal', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('NormalFloat', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.libadwaita_popup })
    hl('FloatBorder', { fg = colors.gtk_src_dark.light_3, bg = colors.gtk_src_dark.libadwaita_popup })
    hl('ColorColumn', { bg = colors.gtk_src_dark.libadwaita_dark_alt })
    hl('Cursor', { fg = colors.gtk_src_dark.libadwaita_dark, bg = colors.gtk_src_dark.light_5 })
    hl('CursorLine', { bg = colors.gtk_src_dark.libadwaita_dark_alt })
    hl('CursorColumn', { bg = colors.gtk_src_dark.libadwaita_dark_alt })
    hl('Directory', { fg = colors.gtk_src_dark.light_1, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('DiffAdd', { fg = colors.gtk_src_dark.teal_3, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('DiffChange', { fg = colors.gtk_src_dark.orange_3, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('DiffDelete', { fg = colors.gtk_src_dark.red_1, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('DiffText', { fg = colors.gtk_src_dark.violet_2, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('EndOfBuffer', { fg = colors.gtk_src_dark.libadwaita_dark, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('ErrorMsg', { fg = colors.gtk_src_dark.red_3, bg = colors.gtk_src_dark.libadwaita_dark, underline = true })
    hl('VertSplit', { fg = colors.gtk_src_dark.split_and_borders, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('WinSeparator', { link = 'VertSplit' })
    hl('Folded', { fg = colors.gtk_src_dark.dark_1, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('FoldColumn', { fg = colors.gtk_src_dark.dark_1, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('SignColumn', { fg = colors.gtk_src_dark.dark_2, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('IncSearch', { fg = colors.gtk_src_dark.dark_4, bg = colors.gtk_src_dark.yellow_4 })
    hl('LineNr', { fg = colors.gtk_src_dark.dark_2, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('CursorLineNr', {
        fg = colors.gtk_src_dark.light_7,
        bg = vim.g.adwaita_disable_cursorline and 'NONE' or colors.gtk_src_dark.libadwaita_dark_alt,
    })
    hl('MatchParen', { fg = colors.gtk_src_dark.light_4, bold = true })
    hl('ModeMsg', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.libadwaita_dark_alt })
    hl('MoreMsg', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.libadwaita_dark_alt })
    hl('NonText', { fg = colors.gtk_src_dark.dark_4 })
    hl('Pmenu', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.libadwaita_popup })
    hl('PmenuSel', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.menu_selected })
    hl('PmenuSbar', { bg = colors.gtk_src_dark.dark_3 })
    hl('PmenuThumb', { bg = colors.gtk_src_dark.dark_1 })
    hl('Question', { fg = colors.gtk_src_dark.blue_1, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('Search', { fg = colors.gtk_src_dark.dark_4, bg = colors.gtk_src_dark.yellow_4 })
    hl('SpecialKey', { fg = colors.gtk_src_dark.dark_2, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('StatusLine', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.libadwaita_dark_alt })
    hl('StatusLineNC', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('Tabline', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.libadwaita_dark_alt })
    hl('TablineFill', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.libadwaita_dark_alt })
    hl('TablineSel', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('Title', { bold = true })
    hl('Visual', { bg = colors.gtk_src_dark.blue_7 })
    hl('VisualNOS', { bg = colors.gtk_src_dark.blue_7 })
    hl('WarningMsg', { fg = colors.gtk_src_dark.yellow_4, bold = true })
    hl('WildMenu', { fg = colors.gtk_src_dark.light_4, bg = colors.gtk_src_dark.blue_5 })

    -- Syntax highlight
    hl('Comment', { fg = colors.gtk_src_dark.dark_2 })
    hl('Constant', { fg = colors.gtk_src_dark.violet_2 })
    hl('String', { fg = colors.gtk_src_dark.teal_2 })
    hl('Character', { fg = colors.gtk_src_dark.teal_3 })
    hl('Number', { fg = colors.gtk_src_dark.violet_4 })
    hl('Boolean', { fg = colors.gtk_src_dark.purple_2, bold = true })
    hl('Float', { fg = colors.gtk_src_dark.teal_3 })
    hl('Identifier', { fg = colors.gtk_src_dark.orange_2 })
    hl('Function', { fg = colors.gtk_src_dark.chameleon_3 })
    hl('Statement', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('Conditional', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('Repeat', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('Label', { fg = colors.gtk_src_dark.purple_2 })
    hl('Operator', { fg = colors.gtk_src_dark.purple_2 })
    hl('Keyword', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('Exception', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('PreProc', { fg = colors.gtk_src_dark.orange_2 })
    hl('Include', { fg = colors.gtk_src_dark.orange_2 })
    hl('Define', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('Macro', { fg = colors.gtk_src_dark.orange_2 })
    hl('PreCondit', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('Type', { fg = colors.gtk_src_dark.light_4 })
    hl('StorageClass', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('Structure', { fg = colors.gtk_src_dark.teal_2, bold = true })
    hl('TypeDef', { fg = colors.gtk_src_dark.light_4, bold = true })
    hl('Special', { fg = colors.gtk_src_dark.blue_2 })
    hl('SpecialChar', { fg = colors.gtk_src_dark.blue_2 })
    hl('Tag', { fg = colors.gtk_src_dark.teal_2 })
    hl('Delimiter', { fg = colors.gtk_src_dark.teal_2 })
    hl('SpecialComment', { fg = colors.gtk_src_dark.dark_2, bold = true })
    hl('Debug', { fg = colors.gtk_src_dark.yellow_2 })
    hl('Underlined', { underline = true })
    hl('Ignore', { fg = colors.gtk_src_dark.light_4 })
    hl('Error', { fg = colors.gtk_src_dark.red_3, underline = true })
    hl('SpellBad', { fg = colors.gtk_src_dark.red_3, underline = true, sp = colors.gtk_src_dark.red_3 })
    hl('SpellCap', { fg = colors.gtk_src_dark.red_3, underline = true, sp = colors.gtk_src_dark.red_3 })
    hl('SpellRare', { fg = colors.gtk_src_dark.red_3, underline = true, sp = colors.gtk_src_dark.red_3 })
    hl('SpellLocale', { fg = colors.gtk_src_dark.red_3, underline = true, sp = colors.gtk_src_dark.red_3 })
    hl('Todo', { fg = colors.gtk_src_dark.yellow_2, bold = true })
    hl('Whitespace', { fg = colors.gtk_src_dark.dark_4 })

    --- Treesitter highlight
    hl('@error', { fg = colors.gtk_src_dark.red_3 })
    hl('@text.literal', { fg = colors.gtk_src_dark.light_4 })
    hl('@text.literal.markdown', { fg = colors.gtk_src_dark.light_4 })
    hl('@text.literal.markdown.inline', { fg = colors.gtk_src_dark.light_4 })
    hl('@text.title', { fg = colors.gtk_src_dark.teal_2, bold = true })
    hl('@text.emphasis', { fg = colors.gtk_src_dark.teal_2, italic = true })
    hl('@text.strong', { fg = colors.gtk_src_dark.teal_2, bold = true })
    hl('@text.uri', { fg = colors.gtk_src_dark.blue_3, underline = true })
    hl('@textReference', { fg = colors.gtk_src_dark.blue_3 })
    hl('@text.underline', { underline = true })
    hl('@text.todo', { fg = colors.gtk_src_dark.yellow_2, bold = true })
    hl('@text.note', { fg = colors.gtk_src_dark.green_3, bold = true })
    hl('@text.warning', { fg = colors.gtk_src_dark.yellow_2, bold = true })
    hl('@text.danger', { fg = colors.gtk_src_dark.red_3, bold = true })
    hl('@comment', { fg = colors.gtk_src_dark.dark_2 })
    hl('@punctuation', { fg = colors.gtk_src_dark.light_4 })
    hl('@punctuation.special', { fg = colors.gtk_src_dark.teal_2 })
    hl('@punctuation.bracket', { fg = colors.gtk_src_dark.light_4 })
    hl('@punctuation.delimiter', { fg = colors.gtk_src_dark.light_4 })
    hl('@constant', { fg = colors.gtk_src_dark.violet_2 })
    hl('@constant.builtin', { fg = colors.gtk_src_dark.violet_2, bold = true })
    hl('@constant.macro', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@define', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@macro', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@string', { fg = colors.gtk_src_dark.teal_2 })
    hl('@string.escape', { fg = colors.gtk_src_dark.blue_2 })
    hl('@stringEscape', { fg = colors.gtk_src_dark.blue_2 })
    hl('@string.special', { fg = colors.gtk_src_dark.blue_2 })
    hl('@string.regex', { fg = colors.gtk_src_dark.purple_2 })
    hl('@character', { fg = colors.gtk_src_dark.teal_3 })
    hl('@character.special', { fg = colors.gtk_src_dark.blue_2 })
    hl('@number', { fg = colors.gtk_src_dark.violet_4 })
    hl('@boolan', { fg = colors.gtk_src_dark.violet_2, bold = true })
    hl('@float', { fg = colors.gtk_src_dark.teal_3 })
    hl('@function', { fg = colors.gtk_src_dark.light_4 })
    hl('@function.method.call', { fg = colors.gtk_src_dark.chameleon_3 })
    hl('@function.builtin', { fg = colors.gtk_src_dark.chameleon_3 })
    hl('@function.macro', { fg = colors.gtk_src_dark.chameleon_3, bold = true })
    hl('@attribute', { fg = colors.gtk_src_dark.orange_4 })
    hl('@annotation', { fg = colors.gtk_src_dark.yellow_2 })
    hl('@parameter', { fg = colors.gtk_src_dark.light_4 })
    hl('@parameter.reference', { fg = colors.gtk_src_dark.orange_2 })
    hl('@method', { fg = colors.gtk_src_dark.light_4 })
    hl('@method.call', { fg = colors.gtk_src_dark.chameleon_3 })
    hl('@field', { fg = colors.gtk_src_dark.light_4 })
    hl('@property', { fg = colors.gtk_src_dark.light_4 })
    hl('@constructor', { fg = colors.gtk_src_dark.light_4 })
    hl('@conditional', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@repeat', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@label', { fg = colors.gtk_src_dark.purple_2 })
    hl('@operator', { fg = colors.gtk_src_dark.purple_2 })
    hl('@keyword', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@keyword.function', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@keyword.operator', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@exception', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@variable', { fg = colors.gtk_src_dark.light_4 })
    hl('@variable.builtin', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@variable.parameter', { fg = colors.gtk_src_dark.light_4 })
    hl('@variable.other', { fg = colors.gtk_src_dark.teal_2 })
    hl('@type', { fg = colors.gtk_src_dark.light_4 })
    hl('@type.builtin', { fg = colors.gtk_src_dark.teal_2, bold = true })
    hl('@type.qualifire', { fg = colors.gtk_src_dark.teal_2 })
    hl('@type.definition', { fg = colors.gtk_src_dark.teal_2, bold = true })
    hl('@storageclass', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@structure', { fg = colors.gtk_src_dark.teal_2, bold = true })
    hl('@namespace', { fg = colors.gtk_src_dark.orange_2 })
    hl('@include', { fg = colors.gtk_src_dark.orange_2, bold = true })
    hl('@preproc', { fg = colors.gtk_src_dark.orange_2 })
    hl('@debug', { fg = colors.gtk_src_dark.yellow_2 })
    hl('@tag', { fg = colors.gtk_src_dark.teal_2 })
    hl('@tag.delimiter', { fg = colors.gtk_src_dark.light_4 })
    hl('@tag.attribute', { fg = colors.gtk_src_dark.orange_2 })

    -- LSP semantic tokens
    hl('@lsp.type.class', { link = '@type' })
    hl('@lsp.type.decorator', { link = '@function' })
    hl('@lsp.type.enum', { link = '@structure' })
    hl('@lsp.type.enumMember', { link = '@property' })
    hl('@lsp.type.function', { link = '@function' })
    hl('@lsp.type.interface', { link = '@type' })
    hl('@lsp.type.macro', { link = '@macro' })
    hl('@lsp.type.method', { link = '@function' })
    hl('@lsp.type.namespace', { link = '@namespace' })
    hl('@lsp.type.parameter', { link = '@parameter' })
    hl('@lsp.type.property', { link = '@property' })
    hl('@lsp.type.struct', { link = '@structure' })
    hl('@lsp.type.type', { link = '@type' })
    hl('@lsp.type.typeParameter', { link = '@type' })
    hl('@lsp.type.variable', { link = '@variable' })
    hl('@lsp.type.keyword', { link = '@keyword' })

    hl('@diff.plus', { link = 'DiffAdd' })
    hl('@diff.minus', { link = 'DiffDelete' })
    hl('@diff.delta', { link = 'DiffChange' })

    hl('@text', { fg = colors.gtk_src_dark.light_4, bg = 'NONE' }) -- Legacy
    hl('@markup.strong', { bold = true })
    hl('@markup.italic', { italic = true })
    hl('@markup.underline', { underline = true })
    hl('@markup.strikethrough', { strikethrough = true })
    hl('@markup.heading', { fg = colors.gtk_src_dark.teal_2, bold = true })
    hl('@markup.raw', { fg = colors.gtk_src_dark.violet_2, bg = 'NONE' })
    hl('@markup.raw.markdown', { fg = colors.gtk_src_dark.violet_2, bg = 'NONE' })
    hl('@markup.raw.markdown_inline', { fg = colors.gtk_src_dark.violet_2, bg = 'NONE' })
    hl('@markup.link.label', { fg = colors.gtk_src_dark.red_2 })
    hl('@markup.link.url', { fg = colors.gtk_src_dark.blue_2 })
    hl('@markup.list.markdown', { fg = colors.gtk_src_dark.orange_4, bold = true })
    hl('@markup.list.checked', { link = 'Todo' })
    hl('@markup.list.unchecked', { link = 'Todo' })
    hl('@textReference', { fg = colors.gtk_src_dark.red_2 })
    hl('@stringEscape', { fg = colors.gtk_src_dark.orange_2, bold = true })

    -- Zig
    hl('@function.call.zig', { fg = colors.gtk_src_dark.chameleon_3 })

    -- Typescript fix
    hl('typescriptParens', { fg = colors.gtk_src_dark.light_4, bg = 'NONE' })
    -- A custome thing to make cmp doc border invisible
    hl('CmpNDocBorder', { fg = colors.gtk_src_dark.split_and_borders, bg = colors.gtk_src_dark.libadwaita_dark })

    hl('htmlTag', { fg = colors.gtk_src_dark.teal_2 })
    hl('htmlEndTag', { fg = colors.gtk_src_dark.teal_2 })
    hl('htmlTagName', { fg = colors.gtk_src_dark.teal_2 })
    hl('htmlSpecialTagName', { fg = colors.gtk_src_dark.teal_2 })
    hl('htmlArg', { fg = colors.gtk_src_dark.orange_2 })

    hl('NvimTreeRootFolder', { fg = colors.gtk_src_dark.light_4 })
    hl('NvimTreeFolderIcon', { fg = colors.gtk_src_dark.light_4 })
    hl('NvimTreeFolderName', { fg = colors.gtk_src_dark.light_4, bold = true })
    hl('NvimTreeEmptyFolderName', { fg = colors.gtk_src_dark.light_4, bold = true })
    hl('NvimTreeOpenedFolderName', { fg = colors.gtk_src_dark.light_4, bold = true })
    hl('NvimTreeVertSplit', { fg = colors.gtk_src_dark.libadwaita_dark, bg = colors.gtk_src_dark.libadwaita_dark })
    hl('NvimTreeNormal', { bg = colors.gtk_src_dark.libadwaita_tree })
    hl('NvimTreeEndOfBuffer', { fg = colors.gtk_src_dark.libadwaita_tree, bg = colors.gtk_src_dark.libadwaita_tree })

    hl('BufferLineIndicatorSelected', { bg = colors.gtk_src_dark.libadwaita_dark })
    hl('BufferLineFill', { bg = colors.gtk_src_dark.libadwaita_dark_alt })

    -- Telescope nvim
    hl('TelescopePromptBorder', { fg = colors.gtk_src_dark.split_and_borders })
    hl('TelescopeResultsBorder', { fg = colors.gtk_src_dark.split_and_borders })
    hl('TelescopePreviewBorder', { fg = colors.gtk_src_dark.split_and_borders })
    hl('TelescopeNormal', { fg = colors.gtk_src_dark.light_4 })
    hl('TelescopeSelection', { fg = colors.gtk_src_dark.light_4 })
    hl('TelescopeMultiSelection', { fg = colors.gtk_src_dark.light_4 })
    hl('TelescopeMatching', { fg = colors.gtk_src_dark.light_4, bold = true })
    hl('TelescopePromptPrefix', { fg = colors.gtk_src_dark.light_4, bold = true })

    hl('LspReferenceText', { bg = colors.gtk_src_dark.blue_7 })
    hl('LspReferenceRead', { bg = colors.gtk_src_dark.blue_7 })
    hl('LspReferenceWrite', { bg = colors.gtk_src_dark.blue_7 })
    hl('DiagnosticError', { fg = colors.gtk_src_dark.red_2 })
    hl('DiagnosticWarn', { fg = colors.gtk_src_dark.yellow_6 })
    hl('DiagnosticHint', { fg = colors.gtk_src_dark.blue_4 })
    hl('DiagnosticInfo', { fg = colors.gtk_src_dark.teal_5 })

    hl('CocHighlightText', { bg = colors.gtk_src_dark.blue_7 })
    hl('CocHighlightRead', { bg = colors.gtk_src_dark.blue_7 })
    hl('CocHighlightWrite', { bg = colors.gtk_src_dark.blue_7 })

    hl('CmpItemKind', { fg = colors.gtk_src_dark.light_4 })

    hl('GitSignsAddLn', { fg = colors.gtk_src_dark.green_2, bg = colors.gtk_src_dark.green_6 })
    hl('GitSignsChangeLn', { fg = colors.gtk_src_dark.orange_1, bg = colors.gtk_src_dark.orange_5 })
    hl('GitSignsCurrentLineBlame', { fg = colors.gtk_src_dark.dark_2 })

    hl('SnacksPicker', { link = 'Normal' })
    hl('SnacksPickerBorder', { link = 'Normal' })
    hl('SnacksPickerDir', { fg = 'NONE', bg = 'NONE', nocombine = true })
    hl('SnacksPickerDirectory', { fg = 'NONE', bg = 'NONE', nocombine = true })
    hl('SnacksIndent', { fg = colors.gtk_src_dark.dark_1, bg = 'NONE', nocombine = true })
    hl('SnacksPickerListCursorLine', { link = 'PmenuSel' })
    hl('SnacksPickerPreviewCursorLine', { fg = 'none', bg = 'none', nocombine = true })

    hl('CompileModeMessage', { underline = true })
    hl('CompileModeMessageRow', { fg = colors.gtk_src_dark.purple_1 })
    hl('CompileModeMessageCol', { fg = colors.gtk_src_dark.green_3 })
    hl('CompileModeError', { fg = colors.gtk_src_dark.red_3 })
    hl('CompileModeWarning', { fg = colors.gtk_src_dark.yellow_6 })
    hl('CompileModeInfo', { fg = colors.gtk_src_dark.green_4 })
    hl('CompileModeCommandOutput', { fg = '#6699ff' })
    hl('CompileModeDirectoryMessage', { fg = '#6699ff' })
    hl('CompileModeOutputFile', { fg = '#9966cc' })
    hl('CompileModeCheckResult', { fg = '#ff9966', bold = true })
    hl('CompileModeCheckTarget', { fg = '#ff9966' })
    hl('CompileModeErrorLocus', { link = 'Visual' })

    hl('BlinkCmpMenu', { link = 'Pmenu' })
    hl('BlinkCmpMenuBorder', { link = 'FloatBorder' })
    hl('BlinkCmpMenuSelection', { link = 'PmenuSel' })
    hl('BlinkCmpScrollBarThumb', { link = 'PmenuThumb' })
    hl('BlinkCmpScrollBarGutter', { link = 'PmenuSbar' })
    hl('BlinkCmpLabel', { fg = colors.gtk_src_dark.light_4, bg = 'NONE' })
    hl('BlinkCmpLabelMatch', { fg = colors.gtk_src_dark.blue_3, bg = 'NONE', bold = true })

    hl('NeogitDiffAdd', { link = 'DiffAdd' })
    hl('NeogitDiffAddHighlight', { link = 'DiffAdd' })
    hl('NeogitDiffDelete', { link = 'DiffDelete' })
    hl('NeogitDiffDeleteHighlight', { link = 'DiffDelete' })
    hl('NeogitDiffContext', { link = 'Normal' })
    hl('NeogitDiffContextHighlight', { link = 'Normal' })
    hl('NeogitDiffAddCursor', { fg = colors.gtk_src_dark.teal_3, bg = colors.gtk_src_dark.libadwaita_dark_alt })
    hl('NeogitDiffContextCursor', { link = 'CursorLine' })
    hl('NeogitDiffDeleteCursor', { fg = colors.gtk_src_dark.red_1, bg = colors.gtk_src_dark.libadwaita_dark_alt })
end

return M
